"""empty message

Revision ID: 76bf7e973de3
Revises: 3d61f24592f4
Create Date: 2024-01-11 15:50:26.374390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bf7e973de3'
down_revision = '3d61f24592f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('terms', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('terms')
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
